server:
  port: 8084
  servlet:
    context-path: /api/v1

spring:
  application:
    name: uzum-notification-service


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

uzum-notification-service:
  eskiz:
    access-token: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3MDUzMjI1MDIsImlhdCI6MTcwMjczMDUwMiwicm9sZSI6InRlc3QiLCJzdWIiOiI1NzI1In0.vJpjKCZ-G98jejSMs2vsKdYOEaJPUR5E1axUnn2Ah90

